### ISSUE TITLE
Update the VIRTUAL_ENV environment variable when finding the venv python binary.

### ISSUE THREAD

**Issue by mkdir700** [rafi/neoconf-venom.nvim#1]
I hope to update the `VIRTUAL_ENV` environment variable when updating the buffer variable. For me personally, one benefit is that when I use toggleterm to open a terminal, the virtual environment will be automatically activated.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/56359329/235581493-7d177565-8ded-48e2-84f9-5b44870502d9.png">

Therefore, a simple solution is to add the line `vim.env.VIRTUAL_ENV = venv_path` in the following code.

https://github.com/rafi/neoconf-venom.nvim/blob/5729df77a7ed83275e527207dc2c2691a2c2da69/lua/venom.lua#L250

What do you think of this proposal?

**Comment by rafi** [comment]
I was considering this, but then realized that when you have multiple projects opened in same nvim session, different virtualenvs can be set in different LSP clients attached to buffers, so setting a _global_ environment variable will lead to confusion. Thoughts?

**Comment by mkdir700** [comment]
According to my personal usage habits, one session corresponds to one project, so I have not experienced the scenario of editing multiple projects in one session.

This mode is similar to opening a project in Pycharm/VSCode, where all py files opened in this workspace use the current interpreter.

Of course, it is not necessary to follow the above-mentioned operating habits. In fact, we should consider under what scenarios global environment variables need to be set. The only scenario I know of is when using toggleterm to open a terminal. Apart from that, I haven't thought of any other usage scenarios yet.

As for automatically activating virtual environments when toggleterm opens a terminal, this can be built into Venom and provided as a configurable option for users.

**Comment by rafi** [comment]
Try this: If you're using lazy.nvim, use following block, and then <kbd>Ctrl</kbd>+<kbd>\\</kbd> in Normal and Terminal modes to toggle terminal. The `VIRTUAL_ENV` variable will propagate if it exists on current buffer.
Let me know what you think...

```lua
return {
	{
		'akinsho/toggleterm.nvim',
		cmd = 'ToggleTerm',
		keys = {
			{ '<C-\\>', mode = { 'n', 't' }, silent = true, function()
				local venv = vim.b['virtual_env']
				local term = require('toggleterm.terminal').Terminal:new({
					env = venv and { VIRTUAL_ENV = venv } or nil,
					count = vim.v.count > 0 and vim.v.count or 1,
				})
				term:toggle()
			end, desc = 'Toggle terminal' },
		},
		opts = {
			open_mapping = false,
		},
	},
}
```

**Comment by mkdir700** [comment]
thank you, This approach is feasible.
