### ISSUE TITLE
Switching before multiple sessions will use the wrong command

### ISSUE THREAD

**Issue by mkdir700** [rafi/neoconf-venom.nvim#4]
I am currently using the plugin [persisted.nvim](https://github.com/olimorris/persisted.nvim) to persistently save each session.

Since it involves switching between multiple sessions, using `table.remove` in the code below is not suitable for the requirement.

https://github.com/rafi/neoconf-venom.nvim/blob/5729df77a7ed83275e527207dc2c2691a2c2da69/lua/venom.lua#L105

An error occurs when switching to another session:

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/56359329/235627155-cf7994d8-36d9-4a4e-a009-232dae7654ad.png">

I can submit a PR to fix this issue. My approach is to make a copy of `cmd` to avoid modifying the original data. Of course, I believe there is a more elegant way to implement this in Lua. I am new to Lua, so if you have any good suggestions, please let me know and I will correct it promptly.

**Comment by rafi** [comment]
Thanks for the report, I've fixed it differently, please see latest `master` and let me know :)
